name: Build Zig SQLite Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, x86_64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Install libyaml & SQLite
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev libsqlite3-dev

      - name: Build SQLite extension
        working-directory: ./markdown_files
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=${{ matrix.arch }}-linux-gnu
        env:
          CC: zig cc -target ${{ matrix.arch }}-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        working_directory: ./markdown_files
        with:
          name: sqlite-extension-${{ matrix.arch }}
          path: zig-out/lib/libmarkdown_files.so
